version: "3"

services:
  backend:
    container_name: owntracks-backend
    image: owntracks-backend:0.1.2
    build: ./backend 
    ports:
      - "8090:8090/tcp"
    volumes:
      - "./backend/data:/data:rw"
    restart: unless-stopped
  
  frontend:
    container_name: owntracks-frontend
    image: owntracks-frontend:0.1.2
    build: ./frontend
    ports:
      - "8080:80/tcp"
    restart: unless-stopped

